### ISSUE TITLE
Replace TOMLJ

### ISSUE THREAD

**Issue by TheButterbrotMan** [bottledspace/ottercraft#15]
https://bytebin.lucko.me/q65N8rvKjG

**Comment by CanadianBaconBoi** [comment]
This is an issue concerning Iris 1.4.0 as it replaces the ANTLR Runtime with a newer version (4) not compatible with the older ATN (3) included with the current version of Ottercraft.

A solution is to downgrade to Iris 1.3.x for the time being.

**Comment by CanadianBaconBoi** [comment]
The problem is deeper, TOMLJ, the TOML library used by this mod hasn't been updated in ages.

The only solution would be for this mod to change it's TOML library,

**Comment by bottledspace** [comment]
> The problem is deeper, TOMLJ, the TOML library used by this mod hasn't been updated in ages.
> 
> The only solution would be for this mod to change it's TOML library,

Thanks for looking into this issue. I'll look around for a modern TOML parser to replace it, I believe that one was simply chosen because it was relatively lightweight and simple to use.

**Comment by bottledspace** [comment]
OK I have decided to switch to JSON for the Fabric version instead, since I already use JSON for the animation and model format. Unfortunately this means the Fabric version will use a different configuration format than Forge, but this seemed like the best option going forward since I am using datapacks for per-world configuration in Forge 1.19.3 anyway.

See the latest release for a build with this change (or on Curseforge in a few days).
